export enum TypeBatchMovement {
  ENTRY = 'ENTRY',
  EXIT = 'EXIT',
}

export enum TypeBatchMovementReason {
  PRODUCTION = 'PRODUCTION',
  MANUAL_DISCARD = 'MANUAL_DISCARD',
  MANUAL_CONSUMPTION = 'MANUAL_CONSUMPTION',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  CORRECTION = 'CORRECTION',
  DELETION = 'DELETION',
  SALE = 'SALE',
  WASTE = 'WASTE',
  LEFTOVER_SOLD_AT_COST = 'LEFTOVER_SOLD_AT_COST',
}
